# Generated by Django 4.1.4 on 2023-01-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
    ]
